name: Daily Email Sender

on:
  schedule:
    - cron: '0 5 * * *'  # 每天5点UTC执行任务
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send email
        run: |
          python -c "
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# 邮件内容
msg = MIMEMultipart()
msg['From'] = '$EMAIL_SENDER'
msg['To'] = '$EMAIL_RECEIVER'
msg['Subject'] = '你好啊'
msg.attach(MIMEText('你好啊', 'plain'))

# 连接SMTP服务器并发送邮件
server = smtplib.SMTP('$SMTP_SERVER', '$SMTP_PORT')
server.starttls()
server.login('$EMAIL_SENDER', '$EMAIL_PASSWORD')
server.sendmail('$EMAIL_SENDER', '$EMAIL_RECEIVER', msg.as_string())
server.quit()
"
        env:
          EMAIL_SENDER: "19536136982@163.com"
          EMAIL_PASSWORD: "CUecL39FchyGt7PE"
          EMAIL_RECEIVER: "778424955@qq.com"
          SMTP_SERVER: "smtp.163.com"  # 以163邮箱为例
          SMTP_PORT: "25"  # 使用 TLS 的端口
