name: Cron Job to Run hello.py and Send Email

on:
  schedule:
    - cron: '7 8 * * *'  # 每天5点（UTC）执行任务
  workflow_dispatch:   # 允许手动触发

jobs:
  run-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
                
      - name: Run hello.py
        run: |
          python hello.py > output.txt
          cat output.txt

      - name: Send email
        run: |
          EMAIL_SENDER="19536136982@163.com"
          EMAIL_PASSWORD="CUecL39FchyGt7PE"
          EMAIL_RECEIVER="778424955@qq.com"
          SUBJECT="Cron Job Output"
          BODY=$(cat output.txt)
          SMTP_SERVER="smtp.163.com"
          SMTP_PORT="25"
          
          python -c "
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# 邮件内容
msg = MIMEMultipart()
msg['From'] = '$EMAIL_SENDER'
msg['To'] = '$EMAIL_RECEIVER'
msg['Subject'] = '$SUBJECT'
msg.attach(MIMEText('$BODY', 'plain'))

# 连接SMTP服务器并发送邮件
server = smtplib.SMTP('$SMTP_SERVER', '$SMTP_PORT')
server.starttls()
server.login('$EMAIL_SENDER', '$EMAIL_PASSWORD')
server.sendmail('$EMAIL_SENDER', '$EMAIL_RECEIVER', msg.as_string())
server.quit()
"
