name: Send Greeting Email

on:
  # 您可以根据需要调整触发条件
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 5 * * *' # 每天午夜 UTC 时间触发

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Send Email
        env:
          EMAIL_SENDER: "19536136982@163.com"
          EMAIL_PASSWORD: "CUecL39FchyGt7PE"
          EMAIL_RECEIVER: "778424955@qq.com"
          SUBJECT: "Cron Job Output"
          BODY: "nihao111"
          SMTP_SERVER: "smtp.163.com"
          SMTP_PORT: "25"
        run: |
          python - c "
          import smtplib
          from email.mime.text import MIMEText
          from email.mime.multipart import MIMEMultipart
          
          # 邮件内容
          msg = MIMEMultipart()
          msg['From'] = '19536136982@163.com'
          msg['To'] = '778424955@qq.com'
          msg['Subject'] = 'Cron Job Output'
          msg.attach(MIMEText('nihao111', 'plain'))
          
          # 连接SMTP服务器并发送邮件
          server = smtplib.SMTP('smtp.163.com', '25')
          # server.starttls()
          server.login('19536136982@163.com', 'CUecL39FchyGt7PE')
          server.sendmail('19536136982@163.com', '778424955@qq.com', msg.as_string())
          server.quit()
          "
